FROM golang:1.23-alpine AS builder

WORKDIR /go/src/testTwoServices
COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN go build -o /app/api-service ./api-service/cmd

FROM alpine:3.19
WORKDIR /app
COPY --from=builder /app/api-service .
ENTRYPOINT ["./api-service"]
