version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: on-failure
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    ports:
      - "50051:50051"
    depends_on:
      - postgres
      - kafka
      - redis
    restart: on-failure
  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: yes
  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: yes
    depends_on:
      - zookeeper
    healthcheck:
      test: [ "CMD-SHELL", "nc -z localhost 9092" ]
      interval: 5s
      timeout: 3s
      retries: 10
    restart: on-failure

volumes:
  pgdata: